/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author pungin
 */
public class 数据加载条 extends javax.swing.JFrame {

    public static final 数据加载条 instance = new 数据加载条();
    private int steps = 1;
    private int step = 1;
    private String title = "";
    private int value = 0;
    private int maximum = 100;
    private int minimum = 0;
    private String text = "";

    /**
     * Creates new form Progressbar
     */
    public 数据加载条() {
        steps = 1;
        step = 1;
        title = "";
        value = 0;
        maximum = 100;
        minimum = 0;
        text = "";
        initComponents();
        数据加载条.setMinimum(0);
        数据加载条.setMaximum(100);
        // 设置当前进度值
        数据加载条.setValue(0);
        // 绘制百分比文本（进度条中间显示的百分数）
        数据加载条.setStringPainted(true);
    }

    @Override
    public void setVisible(boolean bln) {
        if (bln) {
            setLocationRelativeTo(null);
        }
        super.setVisible(bln);
        if (!bln) {
            init();
        }
    }

    private void init() {
        setTitle("", 1);
        setStep(1);
        setText("");
        setMaximum(100);
        setMinimum(0);
        setValue(0);
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public void setTitle(String str) {
        title = str;
        if (steps > 1) {
            str += "(" + step + "/" + steps + ")";
        }
        super.setTitle(str);
    }

    public static void visible(boolean bln) {
        instance.setVisible(bln);
    }

    public static void updateTitle(String str) {
        instance.setTitle(str);
    }

    public static void setTitle(String str, int steps) {
        setSteps(steps);
        instance.setTitle(str);
    }


    public static void setSteps(int steps) {
        instance.steps = steps;
        instance.setTitle(instance.title);
    }

    public static void nextStep() {
        setStep(++instance.step);
    }

    public static void setStep(int step) {
        instance.step = step;
        instance.setTitle(instance.title);
    }

    public static void updateText() {
        setText(instance.text);
    }

    public static void setText(String str) {
        instance.text = str;
        instance.状态信息.setText(instance.text + (getPercent() > -1 ? ("(" + getPercent() + "%)") : ""));
    }

    public static int getPercent() {
        if (instance.maximum <= 0) {
            return -1;
        }
        return (instance.value - instance.minimum) * 100 / instance.maximum;
    }

    public static void addValue() {
        setValue(++instance.value);
    }

    public static void setValue(int i) {
        instance.value = Math.max(Math.min(i, instance.maximum), instance.minimum);
        instance.数据加载条.setValue(instance.value);
        updateText();
    }

    public static int getValue() {
        return instance.value;
    }

    public static void setMaximum(int i) {
        instance.maximum = i;
        instance.数据加载条.setMaximum(instance.maximum);
    }

    public static void setMinimum(int i) {
        instance.minimum = i;
        instance.数据加载条.setMinimum(instance.minimum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AppIcon = new javax.swing.JLabel();
        数据加载条 = new javax.swing.JProgressBar();
        状态信息 = new javax.swing.JLabel();

        AppIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon.png"))); // NOI18N
        AppIcon.setText("jLabel56");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, AppIcon, org.jdesktop.beansbinding.ELProperty.create("${icon.image}"), this, org.jdesktop.beansbinding.BeanProperty.create("iconImage"));
        bindingGroup.addBinding(binding);

        数据加载条.setBorderPainted(false);

        状态信息.setText("状态");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(数据加载条, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(状态信息)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(状态信息)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(数据加载条, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppIcon;
    private javax.swing.JProgressBar 数据加载条;
    private javax.swing.JLabel 状态信息;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public static class 状态信息 {

        public static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public 状态信息() {
        }
    }
}
